stages:
- stage: azureeastus2
  displayName: azureeastus2
  jobs:
  - job: setup
    displayName: Setup resources
    steps:
    - script: |-
        echo "Run ID: $(Build.BuildId)-$(System.JobId)"
        echo "##vso[task.setvariable variable=RUN_ID]$(Build.BuildId)-$(System.JobId)"
      displayName: Set run id
    - script: |-
        run_url="$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs&j=$(System.JobId)"
        echo "Run URL: $run_url"
        echo "##vso[task.setvariable variable=RUN_URL]$run_url"

        code_url="$(Build.Repository.Uri)/commit/$(Build.SourceVersion)"
        echo "Code URL: $code_url"
        echo "##vso[task.setvariable variable=CODE_URL]$code_url"
      displayName: Set Run URL & Code URL
    - script: |-
        test_results_directory=$(Pipeline.Workspace)/s/$(RUN_ID)
        mkdir -p $test_results_directory
        echo "Test Results directory: $test_results_directory"

        test_results_file=$test_results_directory/results.json

        echo "Test Results file: $test_results_file"
        echo "##vso[task.setvariable variable=TEST_RESULTS_FILE]$test_results_file"
      displayName: Set Test Results Directory
    - script: |-
        echo "Script modules directory: $(Pipeline.Workspace)/s/modules/bash"
        echo "##vso[task.setvariable variable=TEST_MODULES_DIR]$(Pipeline.Workspace)/s/modules/bash"
      displayName: Set Script Module Directory
    