trigger: none
schedules:
  - cron: "0 */1 * * *"
    displayName: "Every 1 Hour"
    branches:
      include:
        - anson-l4-proxy
    always: true

variables:
  SCENARIO_TYPE: perf-eval
  SCENARIO_NAME: apiserver-vn10pod100
  SCENARIO_VERSION: main

stages:
  - stage: azure_canadacentral
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - canadacentral
          engine: kperf
          topology: kperf
          matrix:
            workload-low:
              flowcontrol: "workload-low:1000"
              extra_benchmark_subcmd_args: ""
            exempt:
              flowcontrol: "exempt:5"
              extra_benchmark_subcmd_args: ""
          engine_input:
            runner_image: telescope.azurecr.io/oss/kperf:v0.1.3
            benchmark_subcmd: node10_job1_pod100
            benchmark_subcmd_args: "--total 1000"
          max_parallel: 1
          timeout_in_minutes: 360
          credential_type: managed_identity
