trigger: none
schedules:
  - cron: "0 */4 * * *"
    displayName: "Every 4 Hours"
    branches:
      include:
        - anson-l4-proxy
    always: true

variables:
  SCENARIO_TYPE: perf-eval
  SCENARIO_NAME: apiserver-vn100pod10k
  SCENARIO_VERSION: main

stages:
  - stage: azure_canadacentral
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - canadacentral
          engine: kperf
          topology: kperf
          matrix:
            podsize-10k:
              flowcontrol: "workload-low:1000"
              extra_benchmark_subcmd_args: "--padding-bytes=6114"
            podsize-10k-exempt:
              flowcontrol: "exempt:5"
              extra_benchmark_subcmd_args: "--padding-bytes=6114"
            podsize-20k:
              flowcontrol: "workload-low:1000"
              extra_benchmark_subcmd_args: "--padding-bytes=16384"
            podsize-20k-exempt:
              flowcontrol: "exempt:5"
              extra_benchmark_subcmd_args: "--padding-bytes=16384"
          engine_input:
            runner_image: telescope.azurecr.io/oss/kperf:v0.1.2
            benchmark_subcmd: node100_pod10k
            benchmark_subcmd_args: "--total 72000 --deployments=10 --interval 24h --cpu 64 --memory 192"
          max_parallel: 1
          timeout_in_minutes: 760
          credential_type: managed_identity
