trigger: none
schedules:
  - cron: "0 */12 * * *"
    displayName: "Every 12 Hour"
    branches:
      include:
        - main
    always: true

variables:
  SCENARIO_TYPE: perf-eval
  SCENARIO_NAME: cilium-cluster-churn-n1000p50k
  SCENARIO_VERSION: test

stages:
  - stage: aws_eastus1
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: aws
          regions:
            - us-east-1
          engine: clusterloader2
          engine_input:
            image: "ghcr.io/azure/clusterloader2:v20241022"
          topology: slo
          matrix:
            aws_vpc_cni:
              cpu_per_node: 4
              node_count: 100
              node_per_step: 10
              max_pods: 110
              repeats: 1
              scale_timeout: "30m"
              cilium_enabled: False
              enable_karpenter: "true"
              initial_node_count: 6
          max_parallel: 1
          timeout_in_minutes: 720
          credential_type: service_connection
          ssh_key_enabled: false
  - stage: azure_eastus2
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - eastus2
          engine: clusterloader2
          engine_input:
            image: "ghcr.io/azure/clusterloader2:v20241022"
          topology: slo
          matrix:
            azure_cni:
              cpu_per_node: 4
              node_count: 100
              node_per_step: 10
              max_pods: 110
              repeats: 1
              scale_timeout: "30m"
              cilium_enabled: False
              enable_karpenter: "false"
              initial_node_count: 6
            azure_cilium:
              cpu_per_node: 4
              node_count: 100
              node_per_step: 10
              max_pods: 110
              repeats: 1
              scale_timeout: "30m"
              cilium_enabled: True
              network_policy: cilium
              network_dataplane: cilium
              enable_karpenter: "false"
              initial_node_count: 6
          max_parallel: 2
          timeout_in_minutes: 720
          credential_type: service_connection
          ssh_key_enabled: false
